---
title: "Project2"
author: "Shengqi Zhou"
date: "3/29/2020"
output: word_document
---

```{r}
# read data
house <- read.csv("/Users/zshengqi/Desktop/projectdataremoveoutliers.csv")
```

```{r}
# as factor
house$comes_furnished <- as.factor(house$comes_furnished)
head(house)
```

```{r}
attach(house)
plot(price)
```

```{r}
# split data into training and test dataset
library(dplyr)
train = (house$id %% 2 == 0)
house.test = house[!train,]
dim(house.test)
type.test = type[!train]
```

```{r}
# perform LQA
library(MASS) 
lda.fit = lda(type ~ price + sqfeet + beds + baths, data = house, subset = train) 
lda.fit 
```

```{r}
lda.pred=predict(lda.fit, house.test)
names(lda.pred)
lda.class=lda.pred$class
table(lda.class ,type.test)
mean(lda.class == type.test) # correct predictions
mean(lda.class != type.test) # false predictions
```

```{r}
# perform KNN
library(class) 
train.X=cbind(price, sqfeet, beds, baths)[train ,] 
test.X=cbind(price, sqfeet, beds, baths)[!train ,] 
train.type = type[train] 
```

```{r}
set.seed(1) 
knn.pred=knn(train.X,test.X,train.type ,k=1) 
table(knn.pred,type.test)
mean(knn.pred == type.test) 
```

```{r}

```











